function RDH_GUI_3Part()
% RDH_GUI_3PART - Giao diện 3 workflow riêng biệt cho RDH
% Workflow 1: Embedding (Giấu tin)
% Workflow 2: Extraction (Trích xuất)  
% Workflow 3: Recovery (Khôi phục)

% Tạo figure chính
fig = figure('Visible', 'off', ...
             'Position', [100, 100, 1400, 900], ...
             'Name', 'RDH System - 3 Workflows', ...
             'NumberTitle', 'off', ...
             'MenuBar', 'none', ...
             'ToolBar', 'none', ...
             'Resize', 'off', ...
             'Color', [0.97 0.97 0.98], ...
             'CloseRequestFcn', @closeGUI);

% Khởi tạo handles
handles = struct();
handles.current_tab = 1;
handles.embed_data = struct();
handles.extract_data = struct();
handles.recovery_data = struct();

% Tạo Tab Panel chính
tab_panel = uipanel('Parent', fig, ...
                   'Title', '', ...
                   'Units', 'normalized', ...
                   'Position', [0.01 0.01 0.98 0.98], ...
                   'BorderType', 'none');

% Tab buttons
tab_height = 0.06;
tab_width = 0.33;

handles.tab1_btn = uicontrol('Parent', tab_panel, ...
                            'Style', 'pushbutton', ...
                            'String', '1. GIẤU TIN (EMBEDDING)', ...
                            'Units', 'normalized', ...
                            'Position', [0, 1-tab_height, tab_width, tab_height], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [0.2 0.6 0.8], ...
                            'ForegroundColor', 'white', ...
                            'Callback', @(~,~) switchTab(1));

handles.tab2_btn = uicontrol('Parent', tab_panel, ...
                            'Style', 'pushbutton', ...
                            'String', '2. TRÍCH XUẤT (EXTRACTION)', ...
                            'Units', 'normalized', ...
                            'Position', [tab_width, 1-tab_height, tab_width, tab_height], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [0.6 0.6 0.6], ...
                            'ForegroundColor', 'white', ...
                            'Callback', @(~,~) switchTab(2));

handles.tab3_btn = uicontrol('Parent', tab_panel, ...
                            'Style', 'pushbutton', ...
                            'String', '3. KHÔI PHỤC (RECOVERY)', ...
                            'Units', 'normalized', ...
                            'Position', [2*tab_width, 1-tab_height, tab_width, tab_height], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [0.6 0.6 0.6], ...
                            'ForegroundColor', 'white', ...
                            'Callback', @(~,~) switchTab(3));

% Content area
content_area = [0, 0, 1, 1-tab_height];

%% TAB 1: EMBEDDING
handles.tab1_panel = uipanel('Parent', tab_panel, ...
                            'Title', '', ...
                            'Units', 'normalized', ...
                            'Position', content_area, ...
                            'BorderType', 'none', ...
                            'Visible', 'on');

% Tab 1 Content
handles = createTab1Content(handles.tab1_panel, handles);

%% TAB 2: EXTRACTION  
handles.tab2_panel = uipanel('Parent', tab_panel, ...
                            'Title', '', ...
                            'Units', 'normalized', ...
                            'Position', content_area, ...
                            'BorderType', 'none', ...
                            'Visible', 'off');

% Tab 2 Content
handles = createTab2Content(handles.tab2_panel, handles);

%% TAB 3: RECOVERY
handles.tab3_panel = uipanel('Parent', tab_panel, ...
                            'Title', '', ...
                            'Units', 'normalized', ...
                            'Position', content_area, ...
                            'BorderType', 'none', ...
                            'Visible', 'off');

% Tab 3 Content  
handles = createTab3Content(handles.tab3_panel, handles);

% Lưu handles
set(fig, 'UserData', handles);

% Hiển thị GUI
set(fig, 'Visible', 'on');

%% HELPER FUNCTIONS

    function switchTab(tab_num)
        handles = get(gcf, 'UserData');
        
        % Hide all tabs
        set(handles.tab1_panel, 'Visible', 'off');
        set(handles.tab2_panel, 'Visible', 'off');
        set(handles.tab3_panel, 'Visible', 'off');
        
        % Reset button colors
        set(handles.tab1_btn, 'BackgroundColor', [0.6 0.6 0.6]);
        set(handles.tab2_btn, 'BackgroundColor', [0.6 0.6 0.6]);
        set(handles.tab3_btn, 'BackgroundColor', [0.6 0.6 0.6]);
        
        % Show selected tab and highlight button
        switch tab_num
            case 1
                set(handles.tab1_panel, 'Visible', 'on');
                set(handles.tab1_btn, 'BackgroundColor', [0.2 0.6 0.8]);
            case 2
                set(handles.tab2_panel, 'Visible', 'on');
                set(handles.tab2_btn, 'BackgroundColor', [0.2 0.6 0.8]);
            case 3
                set(handles.tab3_panel, 'Visible', 'on');
                set(handles.tab3_btn, 'BackgroundColor', [0.2 0.6 0.8]);
        end
        
        handles.current_tab = tab_num;
        set(gcf, 'UserData', handles);
    end

    function updateMatrixTable(table_handle, img, focus_rc)
        if isempty(table_handle) || ~ishandle(table_handle)
            return;
        end
        if isempty(img)
            set(table_handle, 'Data', []);
            set(table_handle, 'RowName', {});
            set(table_handle, 'ColumnName', {});
            return;
        end

        if nargin < 3 || isempty(focus_rc)
            focus_rc = [1, 1];
        end

        gray_img = getLumaChannel(img);
        gray_img = double(gray_img);
        r = min(10, size(gray_img, 1));
        c = min(10, size(gray_img, 2));

        % Cắt 10x10 từ vùng focus (nếu focus gần biên thì dịch về trong ảnh)
        start_r = max(1, min(focus_rc(1), size(gray_img,1) - r + 1));
        start_c = max(1, min(focus_rc(2), size(gray_img,2) - c + 1));
        preview = gray_img(start_r:start_r+r-1, start_c:start_c+c-1);

        set(table_handle, 'Data', round(preview));
        set(table_handle, 'RowName', arrayfun(@(x) num2str(start_r + x - 1), 1:r, 'UniformOutput', false));
        set(table_handle, 'ColumnName', arrayfun(@(x) num2str(start_c + x - 1), 1:c, 'UniformOutput', false));
    end

    function gray = getLumaChannel(img)
        if ndims(img) == 3
            ycbcr_img = rgb2ycbcr(img);
            gray = ycbcr_img(:,:,1);
        else
            gray = img;
        end
    end

    function updateChangeText(handles, value)
        if isfield(handles, 'embed_change_text') && isgraphics(handles.embed_change_text)
            set(handles.embed_change_text, 'String', sprintf('Pixel thay đổi: %s', value));
        end
    end

    function handles = createTab1Content(parent, handles)
        % TAB 1: EMBEDDING
        
        % Input section
        input_panel = uipanel('Parent', parent, ...
                             'Title', 'Input (Đầu vào)', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.02 0.7 0.46 0.28]);
        
        % Load original image
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Nạp ảnh gốc', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.75 0.4 0.15], ...
                  'FontSize', 10, ...
                  'Callback', @embed_loadOriginalImage);
        
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Ảnh Demo', ...
                  'Units', 'normalized', ...
                  'Position', [0.55 0.75 0.4 0.15], ...
                  'FontSize', 10, ...
                  'Callback', @embed_loadDemoImage);
        
        % Secret data input
        uicontrol('Parent', input_panel, ...
                  'Style', 'text', ...
                  'String', 'Dữ liệu bí mật:', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.55 0.3 0.1], ...
                  'HorizontalAlignment', 'left', ...
                  'FontSize', 10);
        
        handles.embed_secret_edit = uicontrol('Parent', input_panel, ...
                                             'Style', 'edit', ...
                                             'String', 'Đây là dữ liệu bí mật!', ...
                                             'Units', 'normalized', ...
                                             'Position', [0.05 0.4 0.9 0.1], ...
                                             'FontSize', 10, ...
                                             'HorizontalAlignment', 'left');
        
        % Algorithm selection
        uicontrol('Parent', input_panel, ...
                  'Style', 'text', ...
                  'String', 'Thuật toán:', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.25 0.3 0.1], ...
                  'HorizontalAlignment', 'left', ...
                  'FontSize', 10);
        
        handles.embed_algorithm_popup = uicontrol('Parent', input_panel, ...
                                                 'Style', 'popup', ...
                                                 'String', {'Histogram Shifting (HS)', 'Difference Expansion (DE)'}, ...
                                                 'Units', 'normalized', ...
                                                 'Position', [0.4 0.25 0.55 0.1], ...
                                                 'FontSize', 10, ...
                                                 'Value', 1);
        
        % Action buttons
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'THỰC HIỆN GIẤU TIN', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.05 0.9 0.15], ...
                  'FontSize', 12, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.2 0.8 0.2], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @embed_performEmbedding);
        
        % Image display section
        image_panel = uipanel('Parent', parent, ...
                             'Title', 'Hiển thị ảnh', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.5 0.5 0.48 0.48]);
        
        handles.embed_axes_original = axes('Parent', image_panel, ...
                                          'Units', 'normalized', ...
                                          'Position', [0.05 0.55 0.4 0.4]);
        title(handles.embed_axes_original, 'Ảnh gốc', 'FontSize', 10);
        
        handles.embed_axes_watermarked = axes('Parent', image_panel, ...
                                             'Units', 'normalized', ...
                                             'Position', [0.55 0.55 0.4 0.4]);
        title(handles.embed_axes_watermarked, 'Ảnh đã giấu tin', 'FontSize', 10);
        
        % Save section
        save_panel = uipanel('Parent', image_panel, ...
                            'Title', 'Lưu kết quả', ...
                            'Units', 'normalized', ...
                            'Position', [0.05 0.05 0.9 0.45]);
        
        uicontrol('Parent', save_panel, ...
                  'Style', 'pushbutton', ...
                  'String', '💾 LƯU ẢNH ĐÃ GIẤU TIN', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.7 0.9 0.25], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.2 0.6 0.8], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @embed_saveWatermarkedImage);
        
        uicontrol('Parent', save_panel, ...
                  'Style', 'pushbutton', ...
                  'String', '📁 LƯU THÔNG TIN EMBED', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.4 0.9 0.25], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.6 0.4 0.8], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @embed_saveEmbedInfo);
        
        % Info display
        % Matrix preview panel
        matrix_panel = uipanel('Parent', parent, ...
                              'Title', 'Ma trận (preview 10x10)', ...
                              'FontSize', 12, ...
                              'FontWeight', 'bold', ...
                              'Units', 'normalized', ...
                              'Position', [0.02 0.02 0.46 0.48]);

        handles.embed_change_text = uicontrol('Parent', matrix_panel, ...
                                             'Style', 'text', ...
                                             'String', 'Pixel thay đổi: -', ...
                                             'Units', 'normalized', ...
                                             'Position', [0.02 0.9 0.96 0.08], ...
                                             'HorizontalAlignment', 'left', ...
                                             'FontSize', 10, ...
                                             'FontWeight', 'bold');

        uicontrol('Parent', matrix_panel, ...
                  'Style', 'text', ...
                  'String', 'Ảnh gốc (kênh sáng/gray)', ...
                  'Units', 'normalized', ...
                  'Position', [0.02 0.8 0.46 0.1], ...
                  'HorizontalAlignment', 'left', ...
                  'FontSize', 10, ...
                  'FontWeight', 'bold');

        handles.embed_matrix_original_table = uitable('Parent', matrix_panel, ...
                                                     'Units', 'normalized', ...
                                                     'Position', [0.02 0.05 0.46 0.8], ...
                                                     'FontSize', 9);

        uicontrol('Parent', matrix_panel, ...
                  'Style', 'text', ...
                  'String', 'Ảnh sau giấu tin', ...
                  'Units', 'normalized', ...
                  'Position', [0.52 0.8 0.46 0.1], ...
                  'HorizontalAlignment', 'left', ...
                  'FontSize', 10, ...
                  'FontWeight', 'bold');

        handles.embed_matrix_watermarked_table = uitable('Parent', matrix_panel, ...
                                                        'Units', 'normalized', ...
                                                        'Position', [0.52 0.05 0.46 0.8], ...
                                                        'FontSize', 9);

        handles.embed_info_text = uicontrol('Parent', parent, ...
                                           'Style', 'text', ...
                                           'String', '🔒 TAB 1 - GIẤU TIN\n\n📋 HƯỚNG DẪN:\n1. Nạp ảnh gốc (hoặc dùng ảnh Demo)\n2. Nhập dữ liệu bí mật cần giấu\n3. Chọn thuật toán (HS khuyến nghị)\n4. Nhấn "THỰC HIỆN GIẤU TIN"\n5. ⚠️ QUAN TRỌNG: Lưu cả 2 file:\n   • "Lưu ảnh đã giấu tin" → gửi công khai\n   • "Lưu thông tin embed" → giữ bí mật\n\n🔐 LOGIC BẢO MẬT:\n• Ảnh đã giấu tin: Có thể chia sẻ thoải mái\n• File embed: Là "chìa khóa" - phải bảo vệ!', ...
                                           'Units', 'normalized', ...
                                           'Position', [0.5 0.02 0.48 0.48], ...
                                           'HorizontalAlignment', 'left', ...
                                           'BackgroundColor', [0.95 0.95 1], ...
                                           'FontSize', 9);
    end

    function handles = createTab2Content(parent, handles)
        % TAB 2: EXTRACTION
        
        % Input section
        input_panel = uipanel('Parent', parent, ...
                             'Title', 'Input (Nạp dữ liệu)', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.02 0.6 0.46 0.38]);
        
        % Load watermarked image
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', '📷 NẠP ẢNH ĐÃ GIẤU TIN', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.8 0.9 0.15], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.8 0.4 0.2], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @extract_loadWatermarkedImage);
        
        % Load embed info
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Nạp thông tin embed (.mat)', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.6 0.9 0.15], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.6 0.4 0.8], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @extract_loadEmbedInfo);
        
        % Extract button
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'TRÍCH XUẤT DỮ LIỆU', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.35 0.9 0.2], ...
                  'FontSize', 12, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.8 0.2 0.2], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @extract_performExtraction);
        
        % Save extracted data
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Lưu dữ liệu trích xuất', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.1 0.9 0.15], ...
                  'FontSize', 10, ...
                  'Callback', @extract_saveData);
        
        % Image display
        image_panel = uipanel('Parent', parent, ...
                             'Title', 'Hiển thị ảnh', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.5 0.6 0.48 0.38]);
        
        handles.extract_axes_watermarked = axes('Parent', image_panel, ...
                                               'Units', 'normalized', ...
                                               'Position', [0.1 0.2 0.8 0.7]);
        title(handles.extract_axes_watermarked, 'Ảnh đã giấu tin', 'FontSize', 10);
        
        % Result display
        result_panel = uipanel('Parent', parent, ...
                              'Title', 'Kết quả trích xuất', ...
                              'FontSize', 12, ...
                              'FontWeight', 'bold', ...
                              'Units', 'normalized', ...
                              'Position', [0.02 0.02 0.96 0.56]);
        
        % Extracted text
        uicontrol('Parent', result_panel, ...
                  'Style', 'text', ...
                  'String', 'Dữ liệu trích xuất:', ...
                  'Units', 'normalized', ...
                  'Position', [0.02 0.8 0.2 0.15], ...
                  'HorizontalAlignment', 'left', ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold');
        
        handles.extract_result_text = uicontrol('Parent', result_panel, ...
                                               'Style', 'edit', ...
                                               'String', '', ...
                                               'Units', 'normalized', ...
                                               'Position', [0.02 0.6 0.96 0.15], ...
                                               'FontSize', 12, ...
                                               'BackgroundColor', [0.9 1 0.9], ...
                                               'HorizontalAlignment', 'left', ...
                                               'Max', 2);
        
        % Info display
        handles.extract_info_text = uicontrol('Parent', result_panel, ...
                                             'Style', 'text', ...
                                             'String', '🔓 TAB 2 - TRÍCH XUẤT\n\n📋 HƯỚNG DẪN:\n1. "Nạp ảnh đã giấu tin" → file .png/.jpg\n2. "Nạp thông tin embed" → file .mat (chìa khóa)\n3. Nhấn "TRÍCH XUẤT DỮ LIỆU"\n4. Xem dữ liệu bí mật được trích xuất\n5. (Tùy chọn) "Lưu dữ liệu trích xuất" → file .txt\n\n🔐 LOGIC BẢO MẬT:\n• CHỈ DÙNG: Ảnh đã giấu tin + File embed\n• KHÔNG CẦN: Ảnh gốc (tránh rò rỉ bảo mật)', ...
                                             'Units', 'normalized', ...
                                             'Position', [0.02 0.02 0.96 0.55], ...
                                             'HorizontalAlignment', 'left', ...
                                             'BackgroundColor', [1 0.95 0.95], ...
                                             'FontSize', 9);
    end

    function handles = createTab3Content(parent, handles)
        % TAB 3: RECOVERY
        
        % Input section
        input_panel = uipanel('Parent', parent, ...
                             'Title', 'Input (Nạp dữ liệu)', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.02 0.7 0.46 0.28]);
        
        % Load watermarked image
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', '📷 NẠP ẢNH ĐÃ GIẤU TIN', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.75 0.9 0.2], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.8 0.4 0.2], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @recovery_loadWatermarkedImage);
        
        % Load embed info
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Nạp thông tin embed (.mat)', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.5 0.9 0.2], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.6 0.4 0.8], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @recovery_loadEmbedInfo);
        
        % Recover button
        uicontrol('Parent', input_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'KHÔI PHỤC ẢNH GỐC', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.05 0.9 0.35], ...
                  'FontSize', 12, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.2 0.7 0.2], ...
                  'ForegroundColor', 'white', ...
                  'Callback', @recovery_performRecovery);
        
        % Image display section
        image_panel = uipanel('Parent', parent, ...
                             'Title', 'So sánh ảnh', ...
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'Units', 'normalized', ...
                             'Position', [0.5 0.4 0.48 0.58]);
        
        handles.recovery_axes_watermarked = axes('Parent', image_panel, ...
                                                'Units', 'normalized', ...
                                                'Position', [0.05 0.55 0.4 0.4]);
        title(handles.recovery_axes_watermarked, 'Ảnh đã giấu tin', 'FontSize', 9);
        
        handles.recovery_axes_recovered = axes('Parent', image_panel, ...
                                              'Units', 'normalized', ...
                                              'Position', [0.55 0.55 0.4 0.4]);
        title(handles.recovery_axes_recovered, 'Ảnh đã khôi phục', 'FontSize', 9);
        
        % Save section
        save_panel = uipanel('Parent', image_panel, ...
                            'Title', 'Lưu kết quả', ...
                            'Units', 'normalized', ...
                            'Position', [0.05 0.05 0.9 0.45]);
        
        uicontrol('Parent', save_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Lưu ảnh đã khôi phục', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.6 0.9 0.35], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'Callback', @recovery_saveRecoveredImage);
        
        % Comparison info
        handles.recovery_comparison_text = uicontrol('Parent', save_panel, ...
                                                    'Style', 'text', ...
                                                    'String', 'Thông tin so sánh sẽ hiển thị ở đây', ...
                                                    'Units', 'normalized', ...
                                                    'Position', [0.05 0.05 0.9 0.5], ...
                                                    'HorizontalAlignment', 'left', ...
                                                    'BackgroundColor', 'white', ...
                                                    'FontSize', 9);
        
        % Info display
        handles.recovery_info_text = uicontrol('Parent', parent, ...
                                              'Style', 'text', ...
                                              'String', '♻️ TAB 3 - KHÔI PHỤC\n\n📋 HƯỚNG DẪN:\n1. "Nạp ảnh đã giấu tin" → file .png/.jpg\n2. "Nạp thông tin embed" → file .mat (chìa khóa)\n3. Nhấn "KHÔI PHỤC ẢNH GỐC"\n4. So sánh ảnh đã giấu tin vs ảnh khôi phục\n5. (Tùy chọn) "Lưu ảnh đã khôi phục"\n\n🔐 LOGIC BẢO MẬT:\n• CHỈ DÙNG: Ảnh đã giấu tin + File embed\n• KHÔNG CẦN: Ảnh gốc (tránh rò rỉ bảo mật)\n• KẾT QUẢ: Khôi phục hoàn hảo 100%!', ...
                                              'Units', 'normalized', ...
                                              'Position', [0.02 0.02 0.46 0.66], ...
                                              'HorizontalAlignment', 'left', ...
                                              'BackgroundColor', [0.95 1 0.95], ...
                                              'FontSize', 9);
    end

%% CALLBACK FUNCTIONS

    function embed_loadOriginalImage(~, ~)
        handles = get(gcf, 'UserData');
        try
            [filename, pathname] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp;*.tif', 'Image Files'}, ...
                'Chọn ảnh gốc');
            
            if filename ~= 0
                filepath = fullfile(pathname, filename);
                handles.embed_data.original_image = imread(filepath);
                
                axes(handles.embed_axes_original);
                imshow(handles.embed_data.original_image);
                title('Ảnh gốc');
                updateMatrixTable(handles.embed_matrix_original_table, handles.embed_data.original_image, [1 1]);
                updateMatrixTable(handles.embed_matrix_watermarked_table, [], []);
                updateChangeText(handles, '-');
                
                set(handles.embed_info_text, 'String', sprintf('Đã nạp ảnh: %s\nKích thước: %dx%d', ...
                    filename, size(handles.embed_data.original_image, 2), size(handles.embed_data.original_image, 1)));
            end
        catch err
            set(handles.embed_info_text, 'String', sprintf('Lỗi nạp ảnh: %s', err.message));
        end
        set(gcf, 'UserData', handles);
    end

    function embed_loadDemoImage(~, ~)
        handles = get(gcf, 'UserData');
        try
            demo_image = create_demo_image();
            handles.embed_data.original_image = demo_image;
            
            axes(handles.embed_axes_original);
            imshow(handles.embed_data.original_image);
            title('Ảnh demo');
            updateMatrixTable(handles.embed_matrix_original_table, handles.embed_data.original_image, [1 1]);
            updateMatrixTable(handles.embed_matrix_watermarked_table, [], []);
            updateChangeText(handles, '-');
            
            set(handles.embed_info_text, 'String', 'Đã nạp ảnh demo thành công!');
        catch err
            set(handles.embed_info_text, 'String', sprintf('Lỗi tạo ảnh demo: %s', err.message));
        end
        set(gcf, 'UserData', handles);
    end

    function embed_performEmbedding(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.embed_data, 'original_image') || isempty(handles.embed_data.original_image)
            set(handles.embed_info_text, 'String', 'Vui lòng nạp ảnh gốc trước!');
            return;
        end
        
        secret_text = get(handles.embed_secret_edit, 'String');
        if isempty(secret_text)
            set(handles.embed_info_text, 'String', 'Vui lòng nhập dữ liệu bí mật!');
            return;
        end
        
        try
            set(handles.embed_info_text, 'String', 'Đang thực hiện giấu tin...');
            drawnow;
            
            % Convert text to binary
            secret_bits = text_to_binary(secret_text);
            secret_bit_length = length(secret_bits);
            
            % Choose algorithm
            algorithm_idx = get(handles.embed_algorithm_popup, 'Value');
            if algorithm_idx == 1 % HS
                [handles.embed_data.watermarked_image, handles.embed_data.embed_info] = ...
                    embed_HS(handles.embed_data.original_image, secret_bits);
                algorithm_name = 'Histogram Shifting';
            else % DE
                [handles.embed_data.watermarked_image, handles.embed_data.embed_info] = ...
                    embed_DE(handles.embed_data.original_image, secret_bits);
                algorithm_name = 'Difference Expansion';
            end
            
            % Display watermarked image
            axes(handles.embed_axes_watermarked);
            imshow(handles.embed_data.watermarked_image);
            title('Ảnh đã giấu tin');
            updateMatrixTable(handles.embed_matrix_watermarked_table, handles.embed_data.watermarked_image);
            updateMatrixTable(handles.embed_matrix_original_table, handles.embed_data.original_image);
            
            % Calculate PSNR
            psnr_value = calculate_psnr(handles.embed_data.original_image, handles.embed_data.watermarked_image);
            
            % Store additional info
            handles.embed_data.secret_text = secret_text;
            handles.embed_data.algorithm = algorithm_name;
            handles.embed_data.psnr = psnr_value;
            
            % Tính số pixel thay đổi dựa trên vị trí embed (chính xác với HS/DE)
            if isfield(handles.embed_data, 'embed_info') && isfield(handles.embed_data.embed_info, 'embedded_locations')
                changed_pixels = size(handles.embed_data.embed_info.embedded_locations, 1);
                if changed_pixels > 0
                    focus_rc = handles.embed_data.embed_info.embedded_locations(1, 1:2);
                else
                    focus_rc = [1, 1];
                end
            elseif isfield(handles.embed_data, 'embed_info') && isfield(handles.embed_data.embed_info, 'locations')
                changed_pixels = size(handles.embed_data.embed_info.locations, 1) * 2; % mỗi cặp 2 pixel thay đổi
                if changed_pixels > 0
                    focus_rc = handles.embed_data.embed_info.locations(1, 1:2);
                else
                    focus_rc = [1, 1];
                end
            else
                % Fallback tính trực tiếp từ ảnh
                orig_gray = getLumaChannel(handles.embed_data.original_image);
                wm_gray = getLumaChannel(handles.embed_data.watermarked_image);
                changed_mask = orig_gray ~= wm_gray;
                changed_pixels = nnz(changed_mask);
                if changed_pixels > 0
                    [first_r, first_c] = find(changed_mask, 1, 'first');
                    focus_rc = [first_r, first_c];
                else
                    focus_rc = [1, 1];
                end
            end

            updateMatrixTable(handles.embed_matrix_watermarked_table, handles.embed_data.watermarked_image, focus_rc);
            updateMatrixTable(handles.embed_matrix_original_table, handles.embed_data.original_image, focus_rc);
            updateChangeText(handles, num2str(changed_pixels));

            set(handles.embed_info_text, 'String', sprintf('Giấu tin thành công!\nThuật toán: %s\nDữ liệu: %d bit\nPSNR: %.2f dB\nPixel thay đổi: %d\nBạn có thể lưu ảnh và thông tin embed.', ...
                algorithm_name, secret_bit_length, psnr_value, changed_pixels));

        catch err
            set(handles.embed_info_text, 'String', sprintf('Lỗi giấu tin: %s', err.message));
        end
        
        set(gcf, 'UserData', handles);
    end

    function embed_saveWatermarkedImage(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.embed_data, 'watermarked_image') || isempty(handles.embed_data.watermarked_image)
            if isfield(handles, 'embed_info_text')
                set(handles.embed_info_text, 'String', 'Chưa có ảnh đã giấu tin để lưu!');
            else
                fprintf('Chưa có ảnh đã giấu tin để lưu!\n');
            end
            return;
        end
        
        [filename, pathname] = uiputfile({'*.png', 'PNG Files (*.png)'; '*.jpg', 'JPEG Files (*.jpg)'}, ...
            'Lưu ảnh đã giấu tin');
        
        if filename ~= 0
            filepath = fullfile(pathname, filename);
            imwrite(handles.embed_data.watermarked_image, filepath);
            if isfield(handles, 'embed_info_text')
                set(handles.embed_info_text, 'String', sprintf('Đã lưu ảnh: %s', filename));
            else
                fprintf('Đã lưu ảnh: %s\n', filename);
            end
        end
    end

    function embed_saveEmbedInfo(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.embed_data, 'embed_info') || isempty(handles.embed_data.embed_info)
            if isfield(handles, 'embed_info_text')
                set(handles.embed_info_text, 'String', 'Chưa có thông tin embed để lưu!');
            else
                fprintf('Chưa có thông tin embed để lưu!\n');
            end
            return;
        end
        
        [filename, pathname] = uiputfile({'*.mat', 'MATLAB Files (*.mat)'}, ...
            'Lưu thông tin embed');
        
        if filename ~= 0
            filepath = fullfile(pathname, filename);
            embed_info = handles.embed_data.embed_info;
            save(filepath, 'embed_info');
            if isfield(handles, 'embed_info_text')
                set(handles.embed_info_text, 'String', sprintf('Đã lưu thông tin embed: %s', filename));
            else
                fprintf('Đã lưu thông tin embed: %s\n', filename);
            end
        end
    end

%% TAB 2 CALLBACKS (EXTRACTION)

    function extract_loadWatermarkedImage(~, ~)
        handles = get(gcf, 'UserData');
        try
            [filename, pathname] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp;*.tif', 'Image Files'}, ...
                'Chọn ảnh đã giấu tin (KHÔNG phải ảnh gốc!)');
            
            if filename ~= 0
                filepath = fullfile(pathname, filename);
                img = imread(filepath);
                
                % KIỂM TRA: Cảnh báo nếu có thể là ảnh gốc
                [~, name, ~] = fileparts(filename);
                is_suspicious = false;
                
                % Kiểm tra tên file có dấu hiệu là ảnh gốc
                suspicious_keywords = {'original', 'goc', 'demo', 'input', 'source'};
                for i = 1:length(suspicious_keywords)
                    if contains(lower(name), suspicious_keywords{i})
                        is_suspicious = true;
                        break;
                    end
                end
                
                if is_suspicious
                    choice = questdlg(sprintf('⚠️ CẢNH BÁO:\nFile "%s" có vẻ như là ảnh gốc!\n\nBạn có chắc đây là ảnh ĐÃ GIẤU TIN?', filename), ...
                        'Xác nhận ảnh', 'Đây là ảnh đã giấu tin', 'Hủy và chọn lại', 'Hủy và chọn lại');
                    if strcmp(choice, 'Hủy và chọn lại')
                        if isfield(handles, 'extract_info_text')
                            set(handles.extract_info_text, 'String', '❌ Đã hủy. Vui lòng chọn ảnh ĐÃ GIẤU TIN!');
                        else
                            fprintf('❌ Đã hủy. Vui lòng chọn ảnh ĐÃ GIẤU TIN!\n');
                        end
                        return;
                    end
                end
                
                handles.extract_data.watermarked_image = img;
                
                axes(handles.extract_axes_watermarked);
                imshow(handles.extract_data.watermarked_image);
                title('Ảnh đã giấu tin');
                
                if isfield(handles, 'extract_info_text')
                    set(handles.extract_info_text, 'String', sprintf('✅ Đã nạp ảnh đã giấu tin: %s\nKích thước: %dx%d\n\n💡 Hãy nạp file thông tin embed tương ứng!', ...
                        filename, size(handles.extract_data.watermarked_image, 2), size(handles.extract_data.watermarked_image, 1)));
                else
                    fprintf('✅ Đã nạp ảnh đã giấu tin: %s\n', filename);
                end
            end
        catch err
            if isfield(handles, 'extract_info_text')
                set(handles.extract_info_text, 'String', sprintf('Lỗi nạp ảnh: %s', err.message));
            else
                fprintf('Lỗi nạp ảnh: %s\n', err.message);
            end
        end
        set(gcf, 'UserData', handles);
    end

    function extract_loadEmbedInfo(~, ~)
        handles = get(gcf, 'UserData');
        try
            [filename, pathname] = uigetfile({'*.mat', 'MATLAB Files (*.mat)'}, ...
                'Chọn file thông tin embed');
            
            if filename ~= 0
                filepath = fullfile(pathname, filename);
                loaded_data = load(filepath);
                if isfield(loaded_data, 'embed_info')
                    handles.extract_data.embed_info = loaded_data.embed_info;
                    set(handles.extract_info_text, 'String', sprintf('Đã nạp thông tin embed: %s\nSẵn sàng trích xuất!', filename));
                else
                    set(handles.extract_info_text, 'String', 'File không chứa thông tin embed hợp lệ!');
                end
            end
        catch err
            set(handles.extract_info_text, 'String', sprintf('Lỗi nạp file: %s', err.message));
        end
        set(gcf, 'UserData', handles);
    end

    function extract_performExtraction(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.extract_data, 'watermarked_image') || isempty(handles.extract_data.watermarked_image)
            set(handles.extract_info_text, 'String', 'Vui lòng nạp ảnh đã giấu tin trước!');
            return;
        end
        
        if ~isfield(handles.extract_data, 'embed_info') || isempty(handles.extract_data.embed_info)
            set(handles.extract_info_text, 'String', 'Vui lòng nạp file thông tin embed trước!');
            return;
        end
        
        try
            set(handles.extract_info_text, 'String', 'Đang trích xuất dữ liệu...');
            drawnow;
            
            % Detect algorithm from embed_info
            if isfield(handles.extract_data.embed_info, 'peak_point')
                % HS algorithm
                [recovered_img, extracted_bits] = extract_HS(handles.extract_data.watermarked_image, handles.extract_data.embed_info);
                algorithm_name = 'Histogram Shifting';
            else
                % DE algorithm
                [recovered_img, extracted_bits] = extract_DE(handles.extract_data.watermarked_image, handles.extract_data.embed_info);
                algorithm_name = 'Difference Expansion';
            end
            
            % Convert bits to text
            extracted_text = binary_to_text(extracted_bits);
            
            % Store results
            handles.extract_data.extracted_text = extracted_text;
            handles.extract_data.recovered_image = recovered_img;
            
            % Display results
            set(handles.extract_result_text, 'String', extracted_text);
            set(handles.extract_info_text, 'String', sprintf('Trích xuất thành công!\nThuật toán: %s\nĐộ dài text: %d ký tự', ...
                algorithm_name, length(extracted_text)));
            
        catch err
            set(handles.extract_info_text, 'String', sprintf('Lỗi trích xuất: %s', err.message));
        end
        
        set(gcf, 'UserData', handles);
    end

    function extract_saveData(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.extract_data, 'extracted_text') || isempty(handles.extract_data.extracted_text)
            set(handles.extract_info_text, 'String', 'Chưa có dữ liệu để lưu!');
            return;
        end
        
        [filename, pathname] = uiputfile({'*.txt', 'Text Files (*.txt)'}, ...
            'Lưu dữ liệu trích xuất');
        
        if filename ~= 0
            filepath = fullfile(pathname, filename);
            fid = fopen(filepath, 'w', 'n', 'UTF-8');
            if fid ~= -1
                fprintf(fid, '%s', handles.extract_data.extracted_text);
                fclose(fid);
                set(handles.extract_info_text, 'String', sprintf('Đã lưu dữ liệu: %s', filename));
            else
                set(handles.extract_info_text, 'String', 'Lỗi ghi file!');
            end
        end
    end

%% TAB 3 CALLBACKS (RECOVERY)

    function recovery_loadWatermarkedImage(~, ~)
        handles = get(gcf, 'UserData');
        try
            [filename, pathname] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp;*.tif', 'Image Files'}, ...
                'Chọn ảnh đã giấu tin (KHÔNG phải ảnh gốc!)');
            
            if filename ~= 0
                filepath = fullfile(pathname, filename);
                img = imread(filepath);
                
                % KIỂM TRA: Cảnh báo nếu có thể là ảnh gốc
                [~, name, ~] = fileparts(filename);
                is_suspicious = false;
                
                % Kiểm tra tên file có dấu hiệu là ảnh gốc
                suspicious_keywords = {'original', 'goc', 'demo', 'input', 'source'};
                for i = 1:length(suspicious_keywords)
                    if contains(lower(name), suspicious_keywords{i})
                        is_suspicious = true;
                        break;
                    end
                end
                
                if is_suspicious
                    choice = questdlg(sprintf('⚠️ CẢNH BÁO:\nFile "%s" có vẻ như là ảnh gốc!\n\nBạn có chắc đây là ảnh ĐÃ GIẤU TIN?', filename), ...
                        'Xác nhận ảnh', 'Đây là ảnh đã giấu tin', 'Hủy và chọn lại', 'Hủy và chọn lại');
                    if strcmp(choice, 'Hủy và chọn lại')
                        if isfield(handles, 'recovery_info_text')
                            set(handles.recovery_info_text, 'String', '❌ Đã hủy. Vui lòng chọn ảnh ĐÃ GIẤU TIN!');
                        else
                            fprintf('❌ Đã hủy. Vui lòng chọn ảnh ĐÃ GIẤU TIN!\n');
                        end
                        return;
                    end
                end
                
                handles.recovery_data.watermarked_image = img;
                
                axes(handles.recovery_axes_watermarked);
                imshow(handles.recovery_data.watermarked_image);
                title('Ảnh đã giấu tin');
                
                if isfield(handles, 'recovery_info_text')
                    set(handles.recovery_info_text, 'String', sprintf('✅ Đã nạp ảnh đã giấu tin: %s\nKích thước: %dx%d\n\n💡 Hãy nạp file thông tin embed tương ứng!', ...
                        filename, size(handles.recovery_data.watermarked_image, 2), size(handles.recovery_data.watermarked_image, 1)));
                else
                    fprintf('✅ Đã nạp ảnh đã giấu tin: %s\n', filename);
                end
            end
        catch err
            if isfield(handles, 'recovery_info_text')
                set(handles.recovery_info_text, 'String', sprintf('Lỗi nạp ảnh: %s', err.message));
            else
                fprintf('Lỗi nạp ảnh: %s\n', err.message);
            end
        end
        set(gcf, 'UserData', handles);
    end

    function recovery_loadEmbedInfo(~, ~)
        handles = get(gcf, 'UserData');
        try
            [filename, pathname] = uigetfile({'*.mat', 'MATLAB Files (*.mat)'}, ...
                'Chọn file thông tin embed');
            
            if filename ~= 0
                filepath = fullfile(pathname, filename);
                loaded_data = load(filepath);
                if isfield(loaded_data, 'embed_info')
                    handles.recovery_data.embed_info = loaded_data.embed_info;
                    set(handles.recovery_info_text, 'String', sprintf('Đã nạp thông tin embed: %s\nSẵn sàng khôi phục!', filename));
                else
                    set(handles.recovery_info_text, 'String', 'File không chứa thông tin embed hợp lệ!');
                end
            end
        catch err
            set(handles.recovery_info_text, 'String', sprintf('Lỗi nạp file: %s', err.message));
        end
        set(gcf, 'UserData', handles);
    end

    function recovery_performRecovery(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.recovery_data, 'watermarked_image') || isempty(handles.recovery_data.watermarked_image)
            set(handles.recovery_info_text, 'String', 'Vui lòng nạp ảnh đã giấu tin trước!');
            return;
        end
        
        if ~isfield(handles.recovery_data, 'embed_info') || isempty(handles.recovery_data.embed_info)
            set(handles.recovery_info_text, 'String', 'Vui lòng nạp file thông tin embed trước!');
            return;
        end
        
        try
            set(handles.recovery_info_text, 'String', 'Đang khôi phục ảnh gốc...');
            drawnow;
            
            % Detect algorithm and recover
            if isfield(handles.recovery_data.embed_info, 'peak_point')
                % HS algorithm
                [recovered_img, ~] = extract_HS(handles.recovery_data.watermarked_image, handles.recovery_data.embed_info);
                algorithm_name = 'Histogram Shifting';
            else
                % DE algorithm
                [recovered_img, ~] = extract_DE(handles.recovery_data.watermarked_image, handles.recovery_data.embed_info);
                algorithm_name = 'Difference Expansion';
            end
            
            % Store result
            handles.recovery_data.recovered_image = recovered_img;
            
            % Display recovered image
            axes(handles.recovery_axes_recovered);
            imshow(recovered_img);
            title('Ảnh đã khôi phục');
            
            % Calculate comparison metrics
            if isequal(size(handles.recovery_data.watermarked_image), size(recovered_img))
                mse = mean((double(handles.recovery_data.watermarked_image(:)) - double(recovered_img(:))).^2);
                if mse == 0
                    comparison_result = 'HOÀN HẢO: Ảnh được khôi phục 100%';
                else
                    psnr_recovery = 10 * log10(255^2 / mse);
                    comparison_result = sprintf('MSE: %.6f\nPSNR: %.2f dB', mse, psnr_recovery);
                end
            else
                comparison_result = 'Kích thước ảnh khác nhau';
            end
            
            set(handles.recovery_comparison_text, 'String', comparison_result);
            set(handles.recovery_info_text, 'String', sprintf('Khôi phục thành công!\nThuật toán: %s\nCó thể lưu ảnh đã khôi phục.', algorithm_name));
            
        catch err
            set(handles.recovery_info_text, 'String', sprintf('Lỗi khôi phục: %s', err.message));
        end
        
        set(gcf, 'UserData', handles);
    end

    function recovery_saveRecoveredImage(~, ~)
        handles = get(gcf, 'UserData');
        
        if ~isfield(handles.recovery_data, 'recovered_image') || isempty(handles.recovery_data.recovered_image)
            set(handles.recovery_info_text, 'String', 'Chưa có ảnh đã khôi phục để lưu!');
            return;
        end
        
        [filename, pathname] = uiputfile({'*.png', 'PNG Files (*.png)'; '*.jpg', 'JPEG Files (*.jpg)'}, ...
            'Lưu ảnh đã khôi phục');
        
        if filename ~= 0
            filepath = fullfile(pathname, filename);
            imwrite(handles.recovery_data.recovered_image, filepath);
            set(handles.recovery_info_text, 'String', sprintf('Đã lưu ảnh đã khôi phục: %s', filename));
        end
    end

    function closeGUI(~, ~)
        delete(gcf);
    end

end
